// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-7x9y6XyPgitTJmg_QARSaEXMxyJOgg',
    appId: '1:251796083367:web:85db6826def4f758680182',
    messagingSenderId: '251796083367',
    projectId: 'daily-task-app-mt-lucas',
    authDomain: 'daily-task-app-mt-lucas.firebaseapp.com',
    storageBucket: 'daily-task-app-mt-lucas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOa86q3G72KsQXtdZr3R0RsFVBo6aU3cs',
    appId: '1:251796083367:android:330ed1cd093e8497680182',
    messagingSenderId: '251796083367',
    projectId: 'daily-task-app-mt-lucas',
    storageBucket: 'daily-task-app-mt-lucas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa7Lg78rMvBSI9HVxbwWdbchhDq-hHgVw',
    appId: '1:251796083367:ios:b429c090d86c0c96680182',
    messagingSenderId: '251796083367',
    projectId: 'daily-task-app-mt-lucas',
    storageBucket: 'daily-task-app-mt-lucas.firebasestorage.app',
    iosBundleId: 'com.example.dailyTask',
  );
}
